package main

import (
  "fmt"
  "net/http"
  "appengine"
  "appengine/datastore"
)

func seedDatastore(w http.ResponseWriter, r *http.Request) {
  ctx := appengine.NewContext(r)
  data := []FLAG{
    {Order: 1, Code: "au", Name: "Australia"},
    {Order: 2, Code: "us", Name: "United States of America"},
    {Order: 3, Code: "lk", Name: "Sri Lanka"},
    {Order: 4, Code: "mk", Name: "Macedonia"},
    {Order: 5, Code: "vu", Name: "Vanuatu"},
    {Order: 6, Code: "it", Name: "Italy"},
    {Order: 7, Code: "ru", Name: "Russia"},
    {Order: 8, Code: "ao", Name: "Angola"},
    {Order: 9, Code: "fr", Name: "France"},
    {Order: 10, Code: "et", Name: "Ethiopia"},
    {Order: 11, Code: "gt", Name: "Guatemala"},
    {Order: 12, Code: "cl", Name: "Chile"},
    {Order: 13, Code: "qa", Name: "Qatar"},
    {Order: 14, Code: "sn", Name: "Senegal"},
    {Order: 15, Code: "cg", Name: "Congo"},
    {Order: 16, Code: "uy", Name: "Uruguay"},
    {Order: 17, Code: "cn", Name: "China"},
    {Order: 18, Code: "ly", Name: "Libya"},
    {Order: 19, Code: "sy", Name: "Syria"},
    {Order: 20, Code: "ht", Name: "Haiti"},
    {Order: 21, Code: "cf", Name: "Central African Republic"},
    {Order: 22, Code: "no", Name: "Norway"},
    {Order: 23, Code: "ci", Name: "Côte d'Ivoire"},
    {Order: 24, Code: "ae", Name: "United Arab Emirates"},
    {Order: 25, Code: "vc", Name: "Saint Vincent and the Grenadines"},
    {Order: 26, Code: "tj", Name: "Tajikistan"},
    {Order: 27, Code: "er", Name: "Eritrea"},
    {Order: 28, Code: "do", Name: "Dominican Republic"},
    {Order: 29, Code: "md", Name: "Moldova"},
    {Order: 30, Code: "ws", Name: "Samoa"},
    {Order: 31, Code: "cy", Name: "Cyprus"},
    {Order: 32, Code: "tr", Name: "Turkey"},
    {Order: 33, Code: "za", Name: "South Africa"},
    {Order: 34, Code: "sa", Name: "Saudi Arabia"},
    {Order: 35, Code: "me", Name: "Montenegro"},
    {Order: 36, Code: "kh", Name: "Cambodia"},
    {Order: 37, Code: "in", Name: "India"},
    {Order: 38, Code: "hn", Name: "Honduras"},
    {Order: 39, Code: "to", Name: "Tonga"},
    {Order: 40, Code: "mh", Name: "Marshall Islands"},
    {Order: 41, Code: "at", Name: "Austria"},
    {Order: 42, Code: "gd", Name: "Grenada"},
    {Order: 43, Code: "mg", Name: "Madagascar"},
    {Order: 44, Code: "lv", Name: "Latvia"},
    {Order: 45, Code: "am", Name: "Armenia"},
    {Order: 46, Code: "mc", Name: "Monaco"},
    {Order: 47, Code: "br", Name: "Brazil"},
    {Order: 48, Code: "zw", Name: "Zimbabwe"},
    {Order: 49, Code: "cv", Name: "Cape Verde"},
    {Order: 50, Code: "om", Name: "Oman"},
    {Order: 51, Code: "mr", Name: "Mauritania"},
    {Order: 52, Code: "tt", Name: "Trinidad and Tobago"},
    {Order: 53, Code: "pg", Name: "Papua New Guinea"},
    {Order: 54, Code: "by", Name: "Belarus"},
    {Order: 55, Code: "es", Name: "Spain"},
    {Order: 56, Code: "cu", Name: "Cuba"},
    {Order: 57, Code: "ua", Name: "Ukraine"},
    {Order: 58, Code: "mm", Name: "Myanmar"},
    {Order: 59, Code: "hu", Name: "Hungary"},
    {Order: 60, Code: "bn", Name: "Brunei"},
    {Order: 61, Code: "kw", Name: "Kuwait"},
    {Order: 62, Code: "ad", Name: "Andorra"},
    {Order: 63, Code: "ph", Name: "Philippines"},
    {Order: 64, Code: "ye", Name: "Yemen"},
    {Order: 65, Code: "al", Name: "Albania"},
    {Order: 66, Code: "bi", Name: "Burundi"},
    {Order: 67, Code: "kp", Name: "North Korea"},
    {Order: 68, Code: "tz", Name: "Tanzania"},
    {Order: 69, Code: "bh", Name: "Bahrain"},
    {Order: 70, Code: "dk", Name: "Denmark"},
    {Order: 71, Code: "ki", Name: "Kiribati"},
    {Order: 72, Code: "dm", Name: "Dominica"},
    {Order: 73, Code: "ke", Name: "Kenya"},
    {Order: 74, Code: "gn", Name: "Guinea"},
    {Order: 75, Code: "be", Name: "Belgium"},
    {Order: 76, Code: "fj", Name: "Fiji"},
    {Order: 77, Code: "py", Name: "Paraguay"},
    {Order: 78, Code: "ma", Name: "Morocco"},
    {Order: 79, Code: "km", Name: "Comoros"},
    {Order: 80, Code: "mn", Name: "Mongolia"},
    {Order: 81, Code: "uz", Name: "Uzbekistan"},
    {Order: 82, Code: "bj", Name: "Benin"},
    {Order: 83, Code: "is", Name: "Iceland"},
    {Order: 84, Code: "pk", Name: "Pakistan"},
    {Order: 85, Code: "tv", Name: "Tuvalu"},
    {Order: 86, Code: "ar", Name: "Argentina"},
    {Order: 87, Code: "af", Name: "Afghanistan"},
    {Order: 88, Code: "vn", Name: "Viet Nam"},
    {Order: 89, Code: "td", Name: "Chad"},
    {Order: 90, Code: "pl", Name: "Poland"},
    {Order: 91, Code: "mz", Name: "Mozambique"},
    {Order: 92, Code: "va", Name: "Holy See"},
    {Order: 93, Code: "tw", Name: "Taiwan"},
    {Order: 94, Code: "az", Name: "Azerbaijan"},
    {Order: 95, Code: "mw", Name: "Malawi"},
    {Order: 96, Code: "de", Name: "Germany"},
    {Order: 97, Code: "ca", Name: "Canada"},
    {Order: 98, Code: "dz", Name: "Algeria"},
    {Order: 99, Code: "dj", Name: "Djibouti"},
    {Order: 100, Code: "li", Name: "Liechtenstein"},
    {Order: 101, Code: "sk", Name: "Slovakia"},
    {Order: 102, Code: "my", Name: "Malaysia"},
    {Order: 103, Code: "cd", Name: "The Democratic Republic of the Congo"},
    {Order: 104, Code: "rs", Name: "Serbia"},
    {Order: 105, Code: "ve", Name: "Venezuela"},
    {Order: 106, Code: "lc", Name: "Saint Lucia"},
    {Order: 107, Code: "la", Name: "Laos"},
    {Order: 108, Code: "sb", Name: "Solomon Islands"},
    {Order: 109, Code: "jo", Name: "Jordan"},
    {Order: 110, Code: "th", Name: "Thailand"},
    {Order: 111, Code: "pw", Name: "Palau"},
    {Order: 112, Code: "sl", Name: "Sierra Leone"},
    {Order: 113, Code: "jm", Name: "Jamaica"},
    {Order: 114, Code: "eh", Name: "Western Sahara"},
    {Order: 115, Code: "ir", Name: "Iran"},
    {Order: 116, Code: "iq", Name: "Iraq"},
    {Order: 117, Code: "kg", Name: "Kyrgyzstan"},
    {Order: 118, Code: "fi", Name: "Finland"},
    {Order: 119, Code: "il", Name: "Israel"},
    {Order: 120, Code: "ng", Name: "Nigeria"},
    {Order: 121, Code: "bg", Name: "Bulgaria"},
    {Order: 122, Code: "pe", Name: "Peru"},
    {Order: 123, Code: "ug", Name: "Uganda"},
    {Order: 124, Code: "gh", Name: "Ghana"},
    {Order: 125, Code: "bf", Name: "Burkina Faso"},
    {Order: 126, Code: "kz", Name: "Kazakhstan"},
    {Order: 127, Code: "bt", Name: "Bhutan"},
    {Order: 128, Code: "bw", Name: "Botswana"},
    {Order: 129, Code: "id", Name: "Indonesia"},
    {Order: 130, Code: "fm", Name: "Federated States of Micronesia"},
    {Order: 131, Code: "ec", Name: "Ecuador"},
    {Order: 132, Code: "ba", Name: "Bosnia and Herzegovina"},
    {Order: 133, Code: "gm", Name: "Gambia"},
    {Order: 134, Code: "eg", Name: "Egypt"},
    {Order: 135, Code: "si", Name: "Slovenia"},
    {Order: 136, Code: "zm", Name: "Zambia"},
    {Order: 137, Code: "bz", Name: "Belize"},
    {Order: 138, Code: "kr", Name: "South Korea"},
    {Order: 139, Code: "gy", Name: "Guyana"},
    {Order: 140, Code: "tl", Name: "Timor-Leste"},
    {Order: 141, Code: "sc", Name: "Seychelles"},
    {Order: 142, Code: "se", Name: "Sweden"},
    {Order: 143, Code: "ro", Name: "Romania"},
    {Order: 144, Code: "sv", Name: "El Salvador"},
    {Order: 145, Code: "ml", Name: "Mali"},
    {Order: 146, Code: "ge", Name: "Georgia"},
    {Order: 147, Code: "ag", Name: "Antigua and Barbuda"},
    {Order: 148, Code: "lr", Name: "Liberia"},
    {Order: 149, Code: "sd", Name: "Sudan"},
    {Order: 150, Code: "ch", Name: "Switzerland"},
    {Order: 151, Code: "cr", Name: "Costa Rica"},
    {Order: 152, Code: "ee", Name: "Estonia"},
    {Order: 153, Code: "st", Name: "Sao Tome and Principle"},
    {Order: 154, Code: "bd", Name: "Bangladesh"},
    {Order: 155, Code: "co", Name: "Colombia"},
    {Order: 156, Code: "mx", Name: "Mexico"},
    {Order: 157, Code: "pa", Name: "Panama"},
    {Order: 158, Code: "cm", Name: "Cameroon"},
    {Order: 159, Code: "ne", Name: "Niger"},
    {Order: 160, Code: "sm", Name: "San Marino"},
    {Order: 161, Code: "sg", Name: "Singapore"},
    {Order: 162, Code: "ls", Name: "Lesotho"},
    {Order: 163, Code: "np", Name: "Nepal"},
    {Order: 164, Code: "mu", Name: "Mauritius"},
    {Order: 165, Code: "pt", Name: "Portugal"},
    {Order: 166, Code: "rw", Name: "Rwanda"},
    {Order: 167, Code: "gq", Name: "Equatorial Guinea"},
    {Order: 168, Code: "ni", Name: "Nicaragua"},
    {Order: 169, Code: "gw", Name: "Guinea-Bissau"},
    {Order: 170, Code: "mt", Name: "Malta"},
    {Order: 171, Code: "gb", Name: "United Kingdom"},
    {Order: 172, Code: "sr", Name: "Suriname"},
    {Order: 173, Code: "sz", Name: "Swaziland"},
    {Order: 174, Code: "bb", Name: "Barbados"},
    {Order: 175, Code: "nl", Name: "Netherlands"},
    {Order: 176, Code: "hr", Name: "Croatia"},
    {Order: 177, Code: "ks", Name: "Kosovo"},
    {Order: 178, Code: "kn", Name: "Saint Kitts and Nevis"},
    {Order: 179, Code: "mv", Name: "Maldives"},
    {Order: 180, Code: "bs", Name: "Bahamas"},
    {Order: 181, Code: "so", Name: "Somalia"},
    {Order: 182, Code: "nz", Name: "New Zealand"},
    {Order: 183, Code: "ie", Name: "Ireland"},
    {Order: 184, Code: "tm", Name: "Turkmenistan"},
    {Order: 185, Code: "lb", Name: "Lebanon"},
    {Order: 186, Code: "lt", Name: "Lithuania"},
    {Order: 187, Code: "na", Name: "Namibia"},
    {Order: 188, Code: "lu", Name: "Luxembourg"},
    {Order: 189, Code: "bo", Name: "Bolivia"},
    {Order: 190, Code: "cz", Name: "Czechia"},
    {Order: 191, Code: "gr", Name: "Greece"},
    {Order: 192, Code: "tg", Name: "Togo"},
    {Order: 193, Code: "jp", Name: "Japan"},
    {Order: 194, Code: "nr", Name: "Nauru"},
    {Order: 195, Code: "tn", Name: "Tunisia"},
    {Order: 196, Code: "ga", Name: "Gabon"},
  }

  for i := 0; i < len(data); i++ {
    key := datastore.NewIncompleteKey(ctx, "Flag", nil)
    if _, err := datastore.Put(ctx, key, &data[i]); err != nil {
      http.Error(w, err.Error(), http.StatusInternalServerError)
      return
    }
  }
  fmt.Fprintf(w, "Done")
}
